---
title: "p8105_hw4_tc2900"
author: "Chen Shaoxuan"
date: "10/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(rnoaa)
library(ggridges)
library(ggthemes)
library(lubridate)
library(DT)
options(tibble.print_min = 10)
```

**In Problem 2, Shaoxuan Chen (tc2900) leads and Zenghui Xue (zx2231) collaborates. **

#Part 1 imput data and tidy data
```{r}

 p_month = data.frame(read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  clean_names() %>% 
  mutate(mon = floor_date(mon, unit = c("month")) ) )
 
# p_month_data = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
 # clean_names() %>% 
 #floor_date(mon, unit = c("year","month","day"))

GDP_data = data.frame(read_csv("./data/fivethirtyeight_datasets/GDP.csv") %>% 
  clean_names() %>% 
  mutate(mon = floor_date(date, unit = c("month")) ) %>% 
    select(-date))

merge_data = data.frame(merge(GDP_data, p_month) %>%
             na.omit() %>% 
             rename("GDP_value" = "value") %>% 
             mutate(president = ifelse(prez_dem == 1, "dem", "gop") ))
head(merge_data, 10)
  

```

#Part 1 Plot data

The following code chunk makes a bar plot showing the GDP_value over time, and color-coded by president.

```{r plotting, message = FALSE, warning = FALSE}
merge_data %>%
  ggplot(aes(x = mon, y = as.numeric(GDP_value), color = president)) +
  geom_bar(stat = "identity", aes(fill = president)) +
  ylim(range(as.numeric(merge_data$GDP_value))) +
  ylab("GDP value") +
  xlab("Time")
```